services:
  apiservice:
    build:
      context: ../src/ApiService
    ports:
      - "5068:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - apiservice

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - prometheus

  traffic:
    image: alpine/curl
    depends_on:
      - apiservice
    entrypoint: sh -c "while true; do curl -s http://apiservice:8080/fast > /dev/null; curl -s http://apiservice:8080/slow > /dev/null; curl -s http://apiservice:8080/error > /dev/null; sleep 1; done"
