services:
  apiservice:
    build:
      context: ../src/ApiService
    ports:
      - "5068:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - providerservice

  providerservice:
    build:
      context: ../src/ProviderService
    ports:
      - "5069:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

  traffic:
    image: alpine/curl
    depends_on:
      - apiservice
    entrypoint: sh -c "while true; do
      curl -s http://apiservice:8080/fast > /dev/null;
      curl -s http://apiservice:8080/slow > /dev/null;
      curl -s http://apiservice:8080/error > /dev/null;
      curl -s http://apiservice:8080/packages > /dev/null;
      sleep 2;
      done"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - apiservice
      - providerservice

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
