services:
  apiservice:
    build:
      context: ../src/ApiService
    ports:
      - "5068:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - providerservice
      - jaeger
      - rabbitmq

  providerservice:
    build:
      context: ../src/ProviderService
    ports:
      - "5069:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - jaeger

  workerservice:
    build:
      context: ../src/WorkerService
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ConnectionStrings__Postgres=Host=postgres;Database=bookings;Username=admin;Password=admin
    depends_on:
      - rabbitmq
      - providerservice
      - jaeger
      - postgres

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bookings
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://admin:admin@postgres:5432/bookings?sslmode=disable
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  traffic:
    image: alpine/curl
    depends_on:
      - apiservice
    entrypoint: sh -c "while true; do
      curl -s http://apiservice:8080/fast > /dev/null;
      curl -s http://apiservice:8080/slow > /dev/null;
      curl -s http://apiservice:8080/error > /dev/null;
      curl -s http://apiservice:8080/packages > /dev/null;
      sleep 2;
      done"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - apiservice
      - providerservice

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-alerts.yml:/etc/grafana/provisioning/alerting/alerts.yml
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  prometheus_data:
  grafana_data:
  postgres_data:
